name: Terraform Deploy (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Escribe DEPLOY para confirmar el deploy"
        required: true
        type: string

permissions:
  contents: read
  actions: write

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_REGION: eu-west-1
      TF_VAR_aws_region: eu-west-1
              
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan 
        run: terraform plan -input=false -no-color -out=tfplan.bin

      - name: Mostrar plan
        run: terraform show -no-color tfplan.bin > tfplan.txt

      - name: Publicar artefacto del plan
        uses: actions/upload-artifact@v4
        with:
          name: plan
          path: poc-infracost/tfplan.txt

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: plan
    if: ${{ github.event.inputs.confirm == 'DEPLOY' }}
    environment:
      name: deploy
    defaults:
      run:
        working-directory: .
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_REGION: eu-west-1
      TF_VAR_aws_region: eu-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Confirmaci√≥n recibida
        run: |
          echo "Confirm=${{ github.event.inputs.confirm }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
